### ISSUE TITLE
Multiple Issues trying to run locally

### ISSUE THREAD

**Issue by cooganb** [PaulRBerg/confidential-tokens#1]
Hi there! I'm having issues with contracts, deploying locally, all sorts of things. I also see some activity on the AZTECprotocol repo. Are you all updating this?

Thanks for this wonderful tutorial!

**Comment by PaulRBerg** [comment]
Hey @cooganb, sorry for the late reply. This tutorial cannot be deployed locally, because otherwise there would've been a lot of contracts to be deployed. I kept it simple and used the following npm packages:

- [@aztec/contract-addresses](https://www.npmjs.com/package/@aztec/contract-addresses/v/1.1.1)
- [@aztec/contract-artifacts](https://www.npmjs.com/package/@aztec/contract-artifacts/v/1.3.0)

We'll publish a starter kit for local development on AZTEC soon. At the moment, what you can do is clone the [monorepo](https://github.com/AztecProtocol/AZTEC) and follow the README of the "protocol" package.
